version: "2"
services:
  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_password

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev

    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_password

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev

    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev

    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev

    ports:
      - 80:80
