name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Run tests
        run: |
          docker build ./client -t kodega/client-tests -f Dockerfile.dev
          docker run kodega/client-tests npm run test -- --coverage
